version: '2'
services:
    gatewayservice-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/GatewayService/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=GatewayService
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
